# Proyecto

## Introducción

## Objetivo

## Hipótesis
El **cambio en la cartera de crédito** mexicana **no es sensible** a cambios **reputacionales** en el sector financiero. En cambio **sí es sensible** a cambios en las variables **macroeconómicas.**

## Fuentes de Información

## Unidad Muestral
**Porcentaje de desgaste o sobrevivencia** de saldo de crédito por tipo de crédito de **mes a mes.**

# Desarrollo de la TAD

## Librerías

In [19]:
%time
# sistema
import os

# manipulacion datos
import pandas as pd
import numpy as np

# graficación
import matplotlib.pyplot as plt
import plotly.express as px
import seaborn as sns

CPU times: user 2 μs, sys: 0 ns, total: 2 μs
Wall time: 3.81 μs

## Importar Datos
Aunque de manera inicial se había utilizado un función generada con Gemini, se opta por usar una función más sencilla propia. De esta manera poder visualizar de manera mas controlada el contenido de cada carpeta y poder segmentar cada origen de datos y su tratamiento previo a la unión de la tablas.

In [20]:
# ruta con archivos
ruta_bases = "/home/brauliocb126/Documents/Diplomado/Proyecto/Bases" #cpu
#ruta_bases = "/home/brauliocbd15/Documents/Diplomado/Proyecto/Bases" #laptop

### Método Gemini

In [21]:
## diccionario dataframes
#dfs = {}
#
## 2. Recorrer de forma recursiva subcarpetas y archivos con os.walk
#for raiz, carpetas, archivos in os.walk(ruta_bases):
#    for archivo in archivos:
#        # Obtener la ruta completa del archivo
#        ruta_completa = os.path.join(raiz, archivo)
#        
#        # Extraer el nombre sin extensión y la extensión en minúsculas
#        nombre_sin_ext, extension = os.path.splitext(archivo)
#        extension = extension.lower()
#
#        try:
#            # Identificar el formato por la extensión
#            if extension in ['.csv', '.txt']:
#                dfs[nombre_sin_ext] = pd.read_csv(ruta_completa)
#            elif extension in ['.parquet', '.pq']:
#                dfs[nombre_sin_ext] = pd.read_parquet(ruta_completa)
#            elif extension in ['.xlsx', '.xls']:
#                dfs[nombre_sin_ext] = pd.read_excel(ruta_completa)
#            elif extension == '.json':
#                dfs[nombre_sin_ext] = pd.read_json(ruta_completa)
#            elif extension in ['.feather', '.ft']:
#                dfs[nombre_sin_ext] = pd.read_feather(ruta_completa)
#            else:
#                print(f"⚠️ Formato omitido: {archivo}")
#                continue
#
#            print(f"✅ Cargado exitosamente: {os.path.relpath(ruta_completa, ruta_bases)}")
#
#        except Exception as e:
#            print(f"❌ Error al cargar {archivo}: {e}")
#
## 3. Ver resumen de bases cargadas
#print("\n--- Resumen de Bases Cargadas ---")
#for nombre, df in dfs.items():
#    print(f"- {nombre}: {df.shape[0]} filas, {df.shape[1]} columnas")

In [22]:
#for nombre_var, df in dfs.items():
#    # Limpiamos el nombre para asegurar que sea un nombre de variable válido en Python
#    nombre_limpio = nombre_var.replace(" ", "_").replace("-", "_")
#    
#    # Asignamos el DataFrame a una variable global con ese nombre
#    globals()[nombre_limpio] = df
#    print(f"Variable creada: {nombre_limpio}")

In [23]:
#nom_bases = list(dfs.keys())
#nom_bases

### Método Humano

### Crédito Banxico

In [24]:
# información de créditos vigentes banxico
ruta_cred_banxico = "/banxico_20260906"

In [26]:
for raiz, carpteas, archivos in os.walk(os.path.join(ruta_bases, ruta_cred_banxico)):
    for i in archivos:
        ruta_full = os.path.join(ruta_bases, ruta_cred_banxico, i)

        nombre, extension = os.path.splitext(i)
        extension = extension.lower()
        
        try:
            if extension in ['.csv', '.txt']:
                nombre = pd.read_csv(ruta_full)
            elif extension in ['.parquet', '.pq']:
                nombre = pd.read_parquet(ruta_full)
            elif extension in ['.xlsx', '.xls']:
                nombre = pd.read_excel(ruta_full)
            elif extension == '.json':
                nomrbe = pd.read_json(ruta_full)
            elif extension in ['.feather', '.ft']:
                nombre = pd.read_feather(ruta_full)
            else:
                print(f"⚠️ Formato omitido: {i}")
                continue

            print(f"✅ Cargado exitosamente: {os.path.relpath(ruta_full, ruta_bases)}")

        except Exception as e:
            print(f"❌ Error al cargar {i}: {e}")

In [16]:
for i in credito_banxico:
    n = i.split(sep="_")[1]
    columnas_credito = {'Banco de México': 'fecha',
                        'Unnamed: 1': 'saldo_vigente_'+n}
    mod =  globals()[i]
    mod.drop(index=np.arange(0,17,1), inplace=True)
    mod.rename(columns=columnas_credito, inplace=True)
    mod['fecha'] = pd.to_datetime(mod['fecha'])
    mod['saldo_vigente_'+n] = mod['saldo_vigente_'+n].astype('float64')
    display(mod)

         fecha  saldo_vigente_personal
17  2011-02-01                 42880.6
18  2011-03-01                 45666.3
19  2011-04-01                 48004.1
20  2011-05-01                 50076.6
21  2011-06-01                 51562.1
..         ...                     ...
198 2026-03-01                284344.0
199 2026-04-01                286438.6
200 2026-05-01                287516.5
201 2026-06-01                290675.2
202 2026-07-01                293220.5

[186 rows x 2 columns]

         fecha  saldo_vigente_hipotecario
17  2003-12-01                   102171.2
18  2004-01-01                   102803.6
19  2004-02-01                   103189.7
20  2004-03-01                   103895.1
21  2004-04-01                   104989.5
..         ...                        ...
284 2026-03-01                  1443593.2
285 2026-04-01                  1465497.0
286 2026-05-01                  1453447.4
287 2026-06-01                  1478693.2
288 2026-07-01                  1466208.2

[272 rows x 2 columns]

         fecha  saldo_vigente_nomina
17  2011-02-01               55270.1
18  2011-03-01               57643.5
19  2011-04-01               60162.7
20  2011-05-01               62340.4
21  2011-06-01               65093.8
..         ...                   ...
198 2026-03-01              433335.2
199 2026-04-01              437512.8
200 2026-05-01              440332.3
201 2026-06-01              443558.5
202 2026-07-01              445857.2

[186 rows x 2 columns]

         fecha  saldo_vigente_consumo
17  2003-12-01                19151.4
18  2004-01-01                19975.3
19  2004-02-01                20626.8
20  2004-03-01                22400.9
21  2004-04-01                23346.9
..         ...                    ...
284 2026-03-01                89320.7
285 2026-04-01                87534.4
286 2026-05-01                86751.1
287 2026-06-01                89672.3
288 2026-07-01                90949.3

[272 rows x 2 columns]

         fecha  saldo_vigente_tarjeta
17  2003-12-01                57924.8
18  2004-01-01                57952.1
19  2004-02-01                58940.4
20  2004-03-01                61107.5
21  2004-04-01                63730.4
..         ...                    ...
284 2026-03-01               671719.8
285 2026-04-01               681828.6
286 2026-05-01               686256.5
287 2026-06-01               693620.0
288 2026-07-01               691823.9

[272 rows x 2 columns]

         fecha  saldo_vigente_hipotecario
17  2003-12-01                    19234.3
18  2004-01-01                    19032.1
19  2004-02-01                    19308.5
20  2004-03-01                    19146.5
21  2004-04-01                    19001.5
..         ...                        ...
284 2026-03-01                    57798.9
285 2026-04-01                    40372.8
286 2026-05-01                    59937.9
287 2026-06-01                    40330.8
288 2026-07-01                    60214.1

[272 rows x 2 columns]

In [17]:
credito_tarjeta_credito.dtypes

fecha                    datetime64[us]
saldo_vigente_tarjeta           float64
dtype: object

### Condusef

### CNSF

### Macro Económicas

#